apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvd-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvd-backend
  template:
    metadata:
      labels:
        app: nvd-backend
    spec:
      containers:
      - name: nvd-backend
        image: erakhi/nvd-backend-data:0.1
        ports:
        - containerPort: 8081
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000


---


apiVersion: v1
kind: Service
metadata:
  name: nvd-backend
spec:
  selector:
    app: nvd-backend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: NodePort


